/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    templates: Template;
    articles: Article;
    'cost-log': CostLog;
    'article-audit': ArticleAudit;
    'brand-voices': BrandVoice;
    'brand-voice-files': BrandVoiceFile;
    'governance-audit': GovernanceAudit;
    'evidence-sources': EvidenceSource;
    'corpus-snapshots': CorpusSnapshot;
    'pipeline-runs': PipelineRun;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'cost-log': CostLogSelect<false> | CostLogSelect<true>;
    'article-audit': ArticleAuditSelect<false> | ArticleAuditSelect<true>;
    'brand-voices': BrandVoicesSelect<false> | BrandVoicesSelect<true>;
    'brand-voice-files': BrandVoiceFilesSelect<false> | BrandVoiceFilesSelect<true>;
    'governance-audit': GovernanceAuditSelect<false> | GovernanceAuditSelect<true>;
    'evidence-sources': EvidenceSourcesSelect<false> | EvidenceSourcesSelect<true>;
    'corpus-snapshots': CorpusSnapshotsSelect<false> | CorpusSnapshotsSelect<true>;
    'pipeline-runs': PipelineRunsSelect<false> | PipelineRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'llm-settings': LlmSetting;
    'information-gain-policy': InformationGainPolicy;
  };
  globalsSelect: {
    'llm-settings': LlmSettingsSelect<false> | LlmSettingsSelect<true>;
    'information-gain-policy': InformationGainPolicySelect<false> | InformationGainPolicySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'content-run': TaskContentRun;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  outline?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dos?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  donts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  example?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * H2 headings every article using this template must contain. The outline is prose guidance; only these are enforced by the structural QA check.
   */
  requiredSections?:
    | {
        heading: string;
        id?: string | null;
      }[]
    | null;
  seoSpec?: {
    titleTagMaxLength?: number | null;
    metaDescriptionMaxLength?: number | null;
    headingStructureRules?: string | null;
    faqRequired?: boolean | null;
    faqMinQuestions?: number | null;
    faqMaxQuestions?: number | null;
    ogTagsRequired?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title?: string | null;
  slug?: string | null;
  keyword: string;
  template?: (number | null) | Template;
  research?: {
    rankingPagesSummary?: string | null;
    commonSubtopics?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    relatedQuestions?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Written by the research stage; see docs/information-gain.md.
     */
    snapshot?: (number | null) | CorpusSnapshot;
    /**
     * Written by the research stage; see docs/information-gain.md.
     */
    queryCluster?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Written by the research stage; see docs/information-gain.md.
     */
    facets?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Written by the research stage; see docs/information-gain.md.
     */
    gaps?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  titleTag?: string | null;
  metaDescription?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: string | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * verified = information-gain PASS (ready to approve). needs_review / blocked = a reviewer must override or send back.
   */
  status:
    | 'topic_selected'
    | 'researched'
    | 'drafted'
    | 'qa_passed'
    | 'verified'
    | 'needs_review'
    | 'blocked'
    | 'needs_revision'
    | 'approved'
    | 'published';
  qaResults?: {
    structural?: {
      passed?: boolean | null;
      violations?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    factCheck?: {
      passed?: boolean | null;
      notes?: string | null;
      sources?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    qualitativeReview?: {
      passed?: boolean | null;
      notes?: string | null;
      /**
       * Brand voice fit 1–5 from the qualitative review. Informational only.
       */
      voiceScore?: number | null;
      voiceNotes?: string | null;
      /**
       * Clear breaches of a "what we are NOT" trait ({trait, excerpt, explanation}[]). Any entry fails QA.
       */
      notTraitViolations?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
  };
  generationModel?: string | null;
  qaModels?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totalCostUsd?: number | null;
  reviewedBy?: string | null;
  reviewNotes?: string | null;
  /**
   * Required to move a needs_review or blocked article to verified. Recorded in the audit trail.
   */
  reviewJustification?: string | null;
  /**
   * Reasons from the last information-gain run or reviewer; injected into the next generate prompt.
   */
  revisionNotes?: string | null;
  /**
   * Times this article was sent back for regeneration. Informational.
   */
  revisionCount?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corpus-snapshots".
 */
export interface CorpusSnapshot {
  id: number;
  keyword: string;
  /**
   * Lower-cased, trimmed keyword used for reuse lookups.
   */
  keywordKey: string;
  country: string;
  capturedAt: string;
  /**
   * empty = unusable, never reused: either no page yielded text (baselineDocCount 0) or pages were read but extraction produced no claims (baselineDocCount > 0).
   */
  status: 'complete' | 'partial' | 'empty';
  pipelineRunId?: string | null;
  snapshotHash?: string | null;
  models?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  queryCluster?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pages?:
    | {
        position?: number | null;
        url: string;
        title?: string | null;
        domain?: string | null;
        domainRating?: number | null;
        fetchStatus: 'ok' | 'failed' | 'skipped';
        failureReason?: string | null;
        chars?: number | null;
        textHash?: string | null;
        /**
         * Readable page text, capped at 24k chars (decision: stored for auditability).
         */
        text?: string | null;
        claimCount?: number | null;
        /**
         * Claims whose excerpt was not found in this page text; counted, not dropped.
         */
        unverifiedExcerptCount?: number | null;
        id?: string | null;
      }[]
    | null;
  internalCorpus?:
    | {
        article: number | Article;
        articleUpdatedAt: string;
        claimCount?: number | null;
        id?: string | null;
      }[]
    | null;
  baselineClaims?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  facets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  gaps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  baselineDocCount?: number | null;
  /**
   * Pages that yielded no text: failed fetches and skipped ones (a PDF, a refused private address) both count. Zero next to status "empty" means the crawl was fine and claim extraction came back empty.
   */
  failedPageCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-log".
 */
export interface CostLog {
  id: number;
  pipelineRunId: string;
  article?: (number | null) | Article;
  stage?:
    | (
        | 'generate'
        | 'factCheck'
        | 'qualitativeReview'
        | 'claimExtraction'
        | 'informationGainJudge'
        | 'evidenceVerification'
        | 'brandVoiceExtract'
      )
    | null;
  provider?: string | null;
  model?: string | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  webSearchRequests?: number | null;
  costUsd?: number | null;
  request?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  response?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-audit".
 */
export interface ArticleAudit {
  id: number;
  article: number | Article;
  event: string;
  summary: string;
  actorType: 'pipeline' | 'user' | 'system';
  actor: string;
  pipelineRunId?: string | null;
  stage?: string | null;
  fromStatus?: string | null;
  toStatus?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-voices".
 */
export interface BrandVoice {
  id: number;
  name: string;
  /**
   * Only the single active record governs the pipeline. Activating one archives the previous active record.
   */
  status: 'draft' | 'active' | 'archived';
  source: 'onboarding' | 'upload';
  /**
   * The uploaded guide this record was extracted from, if any.
   */
  sourceFile?: (number | null) | BrandVoiceFile;
  /**
   * Last completed onboarding step; the stepper resumes from here.
   */
  onboardingStep?: number | null;
  activatedAt?: string | null;
  activatedBy?: string | null;
  essence?: {
    /**
     * What you do and for whom, in one sentence.
     */
    oneLiner?: string | null;
    mission?: string | null;
  };
  /**
   * What the business stands for (e.g. trust, speed). The voice must reflect these.
   */
  coreValues?:
    | {
        value: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  audience?: {
    description?: string | null;
    languageLevel?: ('plain' | 'general' | 'professional' | 'expert') | null;
    interests?: string | null;
    needs?: string | null;
  };
  /**
   * Your brand as a real person at a party: how do they talk, joke, or help others?
   */
  persona?: string | null;
  /**
   * Exactly 3 adjectives that describe the brand, each with a do/don't example.
   */
  voiceAdjectives?:
    | {
        adjective: string;
        description?: string | null;
        doExample?: string | null;
        dontExample?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Longer-form description of the voice, in your own words.
   */
  voiceInOwnWords?: string | null;
  /**
   * Traits to avoid so the team knows the boundaries (e.g. "funny, but not sarcastic").
   */
  notTraits?:
    | {
        trait: string;
        boundaryNote?: string | null;
        id?: string | null;
      }[]
    | null;
  tone?: {
    /**
     * 1 = Formal … 5 = Casual
     */
    formality?: number | null;
    /**
     * 1 = Warm … 5 = Neutral
     */
    warmth?: number | null;
    /**
     * 1 = Bold … 5 = Careful
     */
    boldness?: number | null;
    /**
     * 1 = Enthusiastic … 5 = Matter-of-fact
     */
    energy?: number | null;
  };
  /**
   * Words you love to use.
   */
  preferredWords?:
    | {
        word: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Jargon and words to ban. Enforced by a deterministic QA check on every generated field.
   */
  bannedWords?:
    | {
        word: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Existing on-voice writing, used as examples when generating.
   */
  samples?:
    | {
        title?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Set when the record was extracted from an uploaded guide.
   */
  extraction?: {
    model?: string | null;
    provider?: string | null;
    extractedAt?: string | null;
    sourceChars?: number | null;
    warnings?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-voice-files".
 */
export interface BrandVoiceFile {
  id: number;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance-audit".
 */
export interface GovernanceAudit {
  id: number;
  subject?:
    | ({
        relationTo: 'brand-voices';
        value: number | BrandVoice;
      } | null)
    | ({
        relationTo: 'evidence-sources';
        value: number | EvidenceSource;
      } | null);
  /**
   * Slug of the audited Global, set instead of subject when the record has no id.
   */
  subjectGlobal?: string | null;
  event: string;
  summary: string;
  actorType: 'pipeline' | 'user' | 'system';
  actor: string;
  fromStatus?: string | null;
  toStatus?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-sources".
 */
export interface EvidenceSource {
  id: number;
  /**
   * Hostname without scheme or path, e.g. docs.example.com. Matches that host and its subdomains.
   */
  domain: string;
  /**
   * Source-quality weight used in evidence integrity: first_party_dataset 1.0 · primary 0.95 · official_docs 0.90 · secondary 0.75 · unverified 0.40 · blocked 0. Unlisted domains are capped at secondary.
   */
  qualityClass: 'first_party_dataset' | 'primary' | 'official_docs' | 'secondary' | 'unverified' | 'blocked';
  /**
   * Why this domain carries this weight.
   */
  note?: string | null;
  /**
   * Inactive rows are ignored; the domain falls back to the rubric.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-runs".
 */
export interface PipelineRun {
  id: number;
  runId: string;
  source: 'onboarding' | 'admin' | 'cli';
  status: 'queued' | 'running' | 'succeeded' | 'failed';
  mode: 'mock' | 'live';
  template: number | Template;
  requestedCount: number;
  articles?: (number | Article)[] | null;
  configFingerprint: string;
  configSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  finalStatuses?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorSummary?: string | null;
  requestedBy: string;
  startedAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'content-run';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'content-run') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'cost-log';
        value: number | CostLog;
      } | null)
    | ({
        relationTo: 'article-audit';
        value: number | ArticleAudit;
      } | null)
    | ({
        relationTo: 'brand-voices';
        value: number | BrandVoice;
      } | null)
    | ({
        relationTo: 'brand-voice-files';
        value: number | BrandVoiceFile;
      } | null)
    | ({
        relationTo: 'governance-audit';
        value: number | GovernanceAudit;
      } | null)
    | ({
        relationTo: 'evidence-sources';
        value: number | EvidenceSource;
      } | null)
    | ({
        relationTo: 'corpus-snapshots';
        value: number | CorpusSnapshot;
      } | null)
    | ({
        relationTo: 'pipeline-runs';
        value: number | PipelineRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  outline?: T;
  dos?:
    | T
    | {
        text?: T;
        id?: T;
      };
  donts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  example?: T;
  requiredSections?:
    | T
    | {
        heading?: T;
        id?: T;
      };
  seoSpec?:
    | T
    | {
        titleTagMaxLength?: T;
        metaDescriptionMaxLength?: T;
        headingStructureRules?: T;
        faqRequired?: T;
        faqMinQuestions?: T;
        faqMaxQuestions?: T;
        ogTagsRequired?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  keyword?: T;
  template?: T;
  research?:
    | T
    | {
        rankingPagesSummary?: T;
        commonSubtopics?:
          | T
          | {
              text?: T;
              id?: T;
            };
        relatedQuestions?:
          | T
          | {
              text?: T;
              id?: T;
            };
        snapshot?: T;
        queryCluster?: T;
        facets?: T;
        gaps?: T;
      };
  body?: T;
  titleTag?: T;
  metaDescription?: T;
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  status?: T;
  qaResults?:
    | T
    | {
        structural?:
          | T
          | {
              passed?: T;
              violations?: T;
            };
        factCheck?:
          | T
          | {
              passed?: T;
              notes?: T;
              sources?: T;
            };
        qualitativeReview?:
          | T
          | {
              passed?: T;
              notes?: T;
              voiceScore?: T;
              voiceNotes?: T;
              notTraitViolations?: T;
            };
      };
  generationModel?: T;
  qaModels?: T;
  totalCostUsd?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  reviewJustification?: T;
  revisionNotes?: T;
  revisionCount?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-log_select".
 */
export interface CostLogSelect<T extends boolean = true> {
  pipelineRunId?: T;
  article?: T;
  stage?: T;
  provider?: T;
  model?: T;
  inputTokens?: T;
  outputTokens?: T;
  webSearchRequests?: T;
  costUsd?: T;
  request?: T;
  response?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-audit_select".
 */
export interface ArticleAuditSelect<T extends boolean = true> {
  article?: T;
  event?: T;
  summary?: T;
  actorType?: T;
  actor?: T;
  pipelineRunId?: T;
  stage?: T;
  fromStatus?: T;
  toStatus?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-voices_select".
 */
export interface BrandVoicesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  source?: T;
  sourceFile?: T;
  onboardingStep?: T;
  activatedAt?: T;
  activatedBy?: T;
  essence?:
    | T
    | {
        oneLiner?: T;
        mission?: T;
      };
  coreValues?:
    | T
    | {
        value?: T;
        description?: T;
        id?: T;
      };
  audience?:
    | T
    | {
        description?: T;
        languageLevel?: T;
        interests?: T;
        needs?: T;
      };
  persona?: T;
  voiceAdjectives?:
    | T
    | {
        adjective?: T;
        description?: T;
        doExample?: T;
        dontExample?: T;
        id?: T;
      };
  voiceInOwnWords?: T;
  notTraits?:
    | T
    | {
        trait?: T;
        boundaryNote?: T;
        id?: T;
      };
  tone?:
    | T
    | {
        formality?: T;
        warmth?: T;
        boldness?: T;
        energy?: T;
      };
  preferredWords?:
    | T
    | {
        word?: T;
        note?: T;
        id?: T;
      };
  bannedWords?:
    | T
    | {
        word?: T;
        note?: T;
        id?: T;
      };
  samples?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  extraction?:
    | T
    | {
        model?: T;
        provider?: T;
        extractedAt?: T;
        sourceChars?: T;
        warnings?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-voice-files_select".
 */
export interface BrandVoiceFilesSelect<T extends boolean = true> {
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governance-audit_select".
 */
export interface GovernanceAuditSelect<T extends boolean = true> {
  subject?: T;
  subjectGlobal?: T;
  event?: T;
  summary?: T;
  actorType?: T;
  actor?: T;
  fromStatus?: T;
  toStatus?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-sources_select".
 */
export interface EvidenceSourcesSelect<T extends boolean = true> {
  domain?: T;
  qualityClass?: T;
  note?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corpus-snapshots_select".
 */
export interface CorpusSnapshotsSelect<T extends boolean = true> {
  keyword?: T;
  keywordKey?: T;
  country?: T;
  capturedAt?: T;
  status?: T;
  pipelineRunId?: T;
  snapshotHash?: T;
  models?: T;
  queryCluster?: T;
  pages?:
    | T
    | {
        position?: T;
        url?: T;
        title?: T;
        domain?: T;
        domainRating?: T;
        fetchStatus?: T;
        failureReason?: T;
        chars?: T;
        textHash?: T;
        text?: T;
        claimCount?: T;
        unverifiedExcerptCount?: T;
        id?: T;
      };
  internalCorpus?:
    | T
    | {
        article?: T;
        articleUpdatedAt?: T;
        claimCount?: T;
        id?: T;
      };
  baselineClaims?: T;
  facets?: T;
  gaps?: T;
  baselineDocCount?: T;
  failedPageCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-runs_select".
 */
export interface PipelineRunsSelect<T extends boolean = true> {
  runId?: T;
  source?: T;
  status?: T;
  mode?: T;
  template?: T;
  requestedCount?: T;
  articles?: T;
  configFingerprint?: T;
  configSnapshot?: T;
  finalStatuses?: T;
  warnings?: T;
  errorSummary?: T;
  requestedBy?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Which model handles each step. Each model needs its provider key (ANTHROPIC_API_KEY or OPENAI_API_KEY) in the environment; prices are USD per 1M tokens and feed the cost log.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-settings".
 */
export interface LlmSetting {
  id: number;
  /**
   * Writes the article draft from the template, research, and brand voice. Leave blank to use PIPELINE_MODEL_GENERATE from the environment, or the platform default (Claude Opus 5).
   */
  generateModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Verifies claims with web search during QA. Leave blank to use PIPELINE_MODEL_FACT_CHECK from the environment, or the platform default (Claude Opus 5).
   */
  factCheckModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Judges style guide, template rules, and brand voice fit during QA. Leave blank to use PIPELINE_MODEL_QUALITATIVE_REVIEW from the environment, or the platform default (Claude Opus 5).
   */
  qualitativeReviewModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Decomposes ranking pages, published articles, and drafts into atomic claims and clusters consensus facets. Leave blank to use PIPELINE_MODEL_CLAIM_EXTRACTION from the environment, or the platform default (Claude Opus 5).
   */
  claimExtractionModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Scores draft claims for novelty, relevance, utility, and duplication against the baseline corpus. Leave blank to use PIPELINE_MODEL_INFORMATION_GAIN_JUDGE from the environment, or the platform default (Claude Opus 5).
   */
  informationGainJudgeModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Web-searches evidence for materially novel claims during information-gain review. Leave blank to use PIPELINE_MODEL_EVIDENCE_VERIFICATION from the environment, or the platform default (Claude Opus 5).
   */
  evidenceVerificationModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  /**
   * Turns an uploaded brand guide into a brand voice draft. Leave blank to use BRAND_VOICE_EXTRACT_MODEL from the environment, or the platform default (Claude Opus 5).
   */
  brandVoiceExtractModel?:
    | (
        | 'claude-fable-5'
        | 'claude-opus-5'
        | 'claude-sonnet-5'
        | 'claude-haiku-4-5'
        | 'gpt-5.6-sol'
        | 'gpt-5.6-terra'
        | 'gpt-5.6-luna'
        | 'gpt-5.5'
        | 'gpt-5.4'
        | 'gpt-5.4-mini'
        | 'gpt-5.4-nano'
        | 'gpt-5'
        | 'gpt-5-mini'
        | 'gpt-5-nano'
      )
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Deterministic publication gates applied by the informationGain pipeline stage. Every change is recorded in Governance audits and changes the policy version stamped on future runs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information-gain-policy".
 */
export interface InformationGainPolicy {
  id: number;
  /**
   * Weighted share of consensus facets the draft must cover. Failing this gate → REVISE. Leave blank to use INFORMATION_GAIN_MIN_CONSENSUS_COVERAGE from the environment, or the default 0.75.
   */
  minConsensusCoverage?: number | null;
  /**
   * Verified gain units ÷ potential gain units; low values mean the draft's novelty rests on unsupported claims. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_MIN_VERIFICATION_RATIO from the environment, or the default 0.9.
   */
  minVerificationRatio?: number | null;
  /**
   * Evidence integrity (support × source quality × exactness) required for a materially novel factual or inference claim. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_MIN_NOVEL_FACTUAL_INTEGRITY from the environment, or the default 0.9.
   */
  minNovelFactualIntegrity?: number | null;
  /**
   * Evidence integrity required for materially novel claims containing numbers, dates, or units. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_MIN_NUMERIC_TEMPORAL_INTEGRITY from the environment, or the default 0.95.
   */
  minNumericTemporalIntegrity?: number | null;
  /**
   * Numeric or temporal values in a materially novel claim must match the cited evidence exactly. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_REQUIRE_EXACT_VALUE_MATCH from the environment, or the default true.
   */
  requireExactValueMatch?: ('true' | 'false') | null;
  /**
   * Every materially novel verifiable claim must cite at least one evidence excerpt. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_REQUIRE_EVIDENCE_LINEAGE from the environment, or the default true.
   */
  requireEvidenceLineage?: ('true' | 'false') | null;
  /**
   * Drafts are model-generated, so any claimed first-party test, survey, or dataset is fabricated. Failing this gate → BLOCK. Leave blank to use INFORMATION_GAIN_BLOCK_FIRST_PARTY_MEASUREMENTS from the environment, or the default true.
   */
  blockFirstPartyMeasurements?: ('true' | 'false') | null;
  /**
   * A claim contradicting reliable evidence at or above this probability needs a human decision (it may be legitimately new). Failing this gate → HUMAN_REVIEW. Leave blank to use INFORMATION_GAIN_MAX_CONTRADICTION_PROBABILITY from the environment, or the default 0.25.
   */
  maxContradictionProbability?: number | null;
  /**
   * Novelty at or above this makes a claim "materially novel"; a materially novel inference needs human review. Failing this gate → HUMAN_REVIEW. Leave blank to use INFORMATION_GAIN_MATERIAL_NOVELTY_THRESHOLD from the environment, or the default 0.55.
   */
  materialNoveltyThreshold?: number | null;
  /**
   * Share of draft claims already published on this site at or above this triggers a consolidation review. Failing this gate → HUMAN_REVIEW. Leave blank to use INFORMATION_GAIN_MAX_INTERNAL_DUPLICATION_RATE from the environment, or the default 0.35.
   */
  maxInternalDuplicationRate?: number | null;
  /**
   * Minimum number of materially novel claims with verified evidence. Failing this gate → REVISE. Leave blank to use INFORMATION_GAIN_MIN_VERIFIED_NOVEL_CLAIMS from the environment, or the default 1.
   */
  minVerifiedNovelClaims?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "llm-settings_select".
 */
export interface LlmSettingsSelect<T extends boolean = true> {
  generateModel?: T;
  factCheckModel?: T;
  qualitativeReviewModel?: T;
  claimExtractionModel?: T;
  informationGainJudgeModel?: T;
  evidenceVerificationModel?: T;
  brandVoiceExtractModel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "information-gain-policy_select".
 */
export interface InformationGainPolicySelect<T extends boolean = true> {
  minConsensusCoverage?: T;
  minVerificationRatio?: T;
  minNovelFactualIntegrity?: T;
  minNumericTemporalIntegrity?: T;
  requireExactValueMatch?: T;
  requireEvidenceLineage?: T;
  blockFirstPartyMeasurements?: T;
  maxContradictionProbability?: T;
  materialNoveltyThreshold?: T;
  maxInternalDuplicationRate?: T;
  minVerifiedNovelClaims?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-run".
 */
export interface TaskContentRun {
  input: {
    runId: string;
  };
  output: {
    articleIds:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    finalStatuses:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}